[project]
name = "ecovacs-traccar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "deebot-client",
]

[tool.uv.sources]
deebot-client = { git = "https://github.com/DeebotUniverse/client.py", tag = "16.1.0" }
